USE AP;
GO

CREATE SCHEMA Admin;
GO

ALTER SCHEMA Admin TRANSFER dbo.ContactUpdates;

ALTER USER AAaron WITH DEFAULT_SCHEMA = Admin;

GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE
ON SCHEMA :: Admin
TO AAaron;